package com.example.LibraryCMS.Model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "book_table")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "book_id_gen")
    @SequenceGenerator(name = "book_id_gen", sequenceName = "book_seq", allocationSize = 1)
    private Long id;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "isbn", nullable = false, unique = true)
    private String isbn;

    @Column(name = "summary", length = 2000)
    private String summary;

    @Column(name = "publication_date")
    private LocalDate publicationDate;

    @Column(name = "page_count")
    private Integer pageCount;

    // Assuming a bidirectional Many-to-Many association with Author
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "book_author",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "author_id")
    )
    @JsonIgnoreProperties("books")
    private Set<Author> authors = new HashSet<>();

    // No-argument constructor required by JPA
    public Book() {
    }

    // Parameterized constructor for convenience (optional)
    public Book(String title, String isbn, String summary, LocalDate publicationDate, Integer pageCount) {
        this.title = title;
        this.isbn = isbn;
        this.summary = summary;
        this.publicationDate = publicationDate;
        this.pageCount = pageCount;
    }

    // Getters and setters for each field (can be generated by your IDE or Lombok)
    public Long getId() {return id;}

    public void setId(Long id) {this.id = id;}

    public String getTitle() {return title;}

    public void setTitle(String title) {this.title = title;}

    public String getIsbn() {return isbn;}

    public void setIsbn(String isbn) {this.isbn = isbn;}

    public String getSummary() {return summary;}

    public void setSummary(String summary) {this.summary = summary;}

    public LocalDate getPublicationDate() {return publicationDate;}

    public void setPublicationDate(LocalDate publicationDate) {this.publicationDate = publicationDate;}

    public Integer getPageCount() {return pageCount;}

    public void setPageCount(Integer pageCount) {this.pageCount = pageCount;}

    public Set<Author> getAuthors() {return authors;}

    public void setAuthors(Set<Author> authors) {this.authors = authors;}



}
